### ISSUE TITLE
[Feature Request]  able to move the windows from its bottom 

### ISSUE THREAD

**Issue by DeepBlueBubble** [kaii-lb/YAMFsquared#1]
### 功能描述

Instead of only able to move the windows from its top, I wish it can also be moved by the bottom. Because sometimes the windows may end up in a weird position where the top is unreachable.

**Comment by kaii-lb** [comment]
im gonna try making the window not go past the statusbar or screen edges, that'll fix it. maybe i'll add a "hold and drag" for it too

**Comment by kaii-lb** [comment]
added ability to drag window from bottom left corner, closing this issue.
